export type ExamplePortrait =
  | Readonly<{ status: "available"; src: `/portraits/${string}.png` }>
  | Readonly<{ status: "unavailable"; reason: string; reviewedAt: string }>;

// A missing asset is a reviewed editorial decision, never an implicit default.
export const examplePortraits = {
  "patrick-collison": { status: "available", src: "/portraits/patrick-collison.png" },
  bjork: { status: "available", src: "/portraits/bjork.png" },
  "alan-kay": { status: "available", src: "/portraits/alan-kay.png" },
  "eugene-tssui": { status: "available", src: "/portraits/eugene-tssui.png" },
  "michael-levin": { status: "available", src: "/portraits/michael-levin.png" },
  "christopher-alexander": { status: "available", src: "/portraits/christopher-alexander.png" },
  "andrej-karpathy": { status: "available", src: "/portraits/andrej-karpathy.png" },
  "brian-eno": { status: "available", src: "/portraits/brian-eno.png" },
  "amelia-wattenberger": { status: "available", src: "/portraits/amelia-wattenberger.png" },
  "anil-dash": { status: "available", src: "/portraits/anil-dash.png" },
  "bad-bunny": { status: "available", src: "/portraits/bad-bunny.png" },
  "bret-victor": { status: "available", src: "/portraits/bret-victor.png" },
  "bryan-cantrill": { status: "available", src: "/portraits/bryan-cantrill.png" },
  "burial": { status: "available", src: "/portraits/burial.png" },
  "caterina-barbieri": { status: "available", src: "/portraits/caterina-barbieri.png" },
  "conor-white-sullivan": { status: "available", src: "/portraits/conor-white-sullivan.png" },
  "cory-doctorow": { status: "available", src: "/portraits/cory-doctorow.png" },
  "dan-snaith": { status: "available", src: "/portraits/dan-snaith.png" },
  "daniel-lopatin": { status: "available", src: "/portraits/daniel-lopatin.png" },
  "david-crawshaw": { status: "available", src: "/portraits/david-crawshaw.png" },
  "david-heinemeier-hansson": { status: "available", src: "/portraits/david-heinemeier-hansson.png" },
  "dax-raad": { status: "available", src: "/portraits/dax-raad.png" },
  "dwarkesh-patel": { status: "available", src: "/portraits/dwarkesh-patel.png" },
  "dylan-patel": { status: "available", src: "/portraits/dylan-patel.png" },
  "geoffrey-huntley": { status: "available", src: "/portraits/geoffrey-huntley.png" },
  "geoffrey-litt": { status: "available", src: "/portraits/geoffrey-litt.png" },
  "george-hotz": { status: "available", src: "/portraits/george-hotz.png" },
  "greg-brockman": { status: "available", src: "/portraits/greg-brockman.png" },
  "gwern": { status: "available", src: "/portraits/gwern.png" },
  "jane-manchun-wong": { status: "available", src: "/portraits/jane-manchun-wong.png" },
  "joel-spolsky": { status: "available", src: "/portraits/joel-spolsky.png" },
  "johannes-schickling": { status: "available", src: "/portraits/johannes-schickling.png" },
  "joscha-bach": { status: "available", src: "/portraits/joscha-bach.png" },
  "linus-lee": { status: "available", src: "/portraits/linus-lee.png" },
  "lorenzo-senni": { status: "available", src: "/portraits/lorenzo-senni.png" },
  "mario-zechner": { status: "available", src: "/portraits/mario-zechner.png" },
  "matt-levine": { status: "available", src: "/portraits/matt-levine.png" },
  "mitchell-hashimoto": { status: "available", src: "/portraits/mitchell-hashimoto.png" },
  "patrick-mckenzie": { status: "available", src: "/portraits/patrick-mckenzie.png" },
  "paul-graham": { status: "available", src: "/portraits/paul-graham.png" },
  "peter-steinberger": { status: "available", src: "/portraits/peter-steinberger.png" },
  "pieter-levels": { status: "available", src: "/portraits/pieter-levels.png" },
  "richard-d-james": { status: "available", src: "/portraits/richard-d-james.png" },
  "riley-walz": { status: "available", src: "/portraits/riley-walz.png" },
  "simon-willison": { status: "available", src: "/portraits/simon-willison.png" },
  "steph-ango": { status: "available", src: "/portraits/steph-ango.png" },
  "stephen-wolfram": { status: "available", src: "/portraits/stephen-wolfram.png" },
  "steve-yegge": { status: "available", src: "/portraits/steve-yegge.png" },
  "stewart-brand": { status: "available", src: "/portraits/stewart-brand.png" },
  "terry-davis": { status: "available", src: "/portraits/terry-davis.png" },
  "thomas-ptacek": { status: "available", src: "/portraits/thomas-ptacek.png" },
  "tim-berners-lee": { status: "available", src: "/portraits/tim-berners-lee.png" },
  "tim-hecker": { status: "available", src: "/portraits/tim-hecker.png" },
  "tyler-cowen": { status: "available", src: "/portraits/tyler-cowen.png" },
  "yacine-brahimi": { status: "available", src: "/portraits/yacine-brahimi.png" },
} as const satisfies Readonly<Record<string, ExamplePortrait>>;

export type ExamplePortraitHandle = keyof typeof examplePortraits;
